spring:
  application:
    name: prometeo

  datasource:
    url: jdbc:postgresql://localhost:5432/prometeo
    username: postgres
    password: Drakotako147258369#
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
